[lunchmoney]
title = "Lunchmoney Changelog"
url = "https://feedback.lunchmoney.app/changelog"
entrySelector = ".changelogEntry"
titleSelector = ".titleContainer .title"
linkSelector = ".titleContainer a"
